site_name: Docs OSAI for RSP
site_url: https://arhuici.github.io/osai
site_description: "Primer proyecto del curso de Artificial Intelligence And Open Science In Research Software Engineering"
site_author: "arhuici"

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Features: features.md
  - License: license.md

# P치ginas y documentaci칩n
docs_dir: docs

# Configuraci칩n de la documentaci칩n
plugins:
  - search
